#!/usr/bin/env ruby

require_relative 'include/mySolver'

unless ARGV.count == 1

  $stderr.puts \
<<EOS
With n, natural integer; n <= 2 :
Usage: #{__FILE__} <SUM ( i=[0..n] : a_i * X^i )>
EOS

else
  mySolver = mySolver.new ARGV.shift
end
